### ISSUE TITLE
Is it possible to implement an in-memory version of `RQALSH`?

### ISSUE THREAD

**Issue by JieFengWang** [HuangQiang/RQALSH#2]
Hi, is it possible to implement an in-memory version of `RQALSH`? Since the disk-based search works slower and the memory space of nowadays PC is a trivial problem.

**Comment by HuangQiang** [comment]
Hi Jiefeng,

I have published the memory version of RQALSH in another repo. Please check https://github.com/HuangQiang/RQALSH_Mem. 

Let me know if you have other issues or suggestions. 

Thanks and regards,
Qiang

**Comment by JieFengWang** [comment]
Thanks. I will close this issue now.
